spring:
  application:
    name: urbanmap-api

  datasource:
    url: jdbc:mysql://localhost:3306/urbanmapdb?createDatabaseIfNotExist=true
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 25MB

urbanmap:
  upload:
    dir-imagens: "../imagens"
    dir-usuario: "usuarios"
    dir-locais: "locais"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 5050