spring:
  application:
    name: urbanmap-api

  datasource:
    url: jdbc:mysql://localhost:3306/urbanmapdb?createDatabaseIfNotExist=true
    username: root
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 5050